version: "2"
services:
  app:
    container_name: shopify-monitor-app
    restart: always
    image: "shopify-monitor"
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:xenial
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
